/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import VectorImage from 'src/assets/images/Back_Vector.png';
import Vector1Image from 'src/assets/images/Back_Vector_1.png';
import Vector2Image from 'src/assets/images/Back_Vector_2.png';
import Vector3Image from 'src/assets/images/Back_Vector_3.png';
import Vector4Image from 'src/assets/images/Back_Vector_4.png';
import Vector5Image from 'src/assets/images/Back_Vector_5.png';
import Vector6Image from 'src/assets/images/Back_Vector_6.png';
import Vector7Image from 'src/assets/images/Back_Vector_7.png';
import Vector8Image from 'src/assets/images/Back_Vector_8.png';
import Vector9Image from 'src/assets/images/Back_Vector_9.png';
import { styled } from '@mui/material/styles';
import { BackProps } from 'src/types';

const Back1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `48px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Group: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `225px`,
  height: `215.62px`,
  left: `-50px`,
  top: `-81px`,
});

const Vector: any = styled('img')({
  height: `215.62px`,
  width: `225px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector1: any = styled('img')({
  height: `35.67px`,
  width: `18.66px`,
  position: `absolute`,
  left: `65px`,
  top: `87px`,
});

const Vector2: any = styled('img')({
  height: `215.62px`,
  width: `225px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector3: any = styled('img')({
  height: `215.62px`,
  width: `225px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector4: any = styled('img')({
  height: `215.62px`,
  width: `225px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector5: any = styled('img')({
  height: `215.62px`,
  width: `225px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector6: any = styled('img')({
  height: `215.62px`,
  width: `225px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector7: any = styled('img')({
  height: `215.62px`,
  width: `225px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector8: any = styled('img')({
  height: `215.62px`,
  width: `225px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector9: any = styled('img')({
  height: `215.62px`,
  width: `225px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

function Back(props: BackProps): JSX.Element {
  return (
    <Back1 className={props.className}>
      <Group>
        <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
        <Vector1 src={Vector1Image} loading="lazy" alt={'Vector'} />
        <Vector2 src={Vector2Image} loading="lazy" alt={'Vector'} />
        <Vector3 src={Vector3Image} loading="lazy" alt={'Vector'} />
        <Vector4 src={Vector4Image} loading="lazy" alt={'Vector'} />
        <Vector5 src={Vector5Image} loading="lazy" alt={'Vector'} />
        <Vector6 src={Vector6Image} loading="lazy" alt={'Vector'} />
        <Vector7 src={Vector7Image} loading="lazy" alt={'Vector'} />
        <Vector8 src={Vector8Image} loading="lazy" alt={'Vector'} />
        <Vector9 src={Vector9Image} loading="lazy" alt={'Vector'} />
      </Group>
    </Back1>
  );
}

export default Back;
