/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import InputField from 'src/components/InputField/InputField';
import { IdNumberProps } from 'src/types';

const IdNumber1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: 'auto',
});

const InputField1: any = styled(InputField)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

function IdNumber(props: IdNumberProps): JSX.Element {
  return (
    <IdNumber1 className={props.className}>
      <InputField1 />
    </IdNumber1>
  );
}

export default IdNumber;
