/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import CheckBoxCircle from 'src/components/CheckBoxCircle/CheckBoxCircle';
import { MenuItemProps } from 'src/types';

const StateActive: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(16, 84, 138, 1)`,
  boxSizing: `border-box`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `12px 16px`,
  height: 'auto',
  width: 'fit-content',
});

const CheckBoxCircle1: any = styled(CheckBoxCircle)(({ theme }: any) => ({
  width: `24px`,
  height: `24px`,
  margin: `0px`,
}));

const MenuItem1: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(16, 84, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `uppercase`,
  margin: `0px 0px 0px 8px`,
}));

const CheckBoxCircle2: any = styled(CheckBoxCircle)(({ theme }: any) => ({
  width: `24px`,
  height: `24px`,
  margin: `0px 0px 0px 8px`,
}));

function MenuItem(props: MenuItemProps): JSX.Element {
  return (
    <StateActive className={props.className}>
      <CheckBoxCircle1 />
      <MenuItem1>{`Menu Item`}</MenuItem1>
      {false && <CheckBoxCircle2 />}
    </StateActive>
  );
}

export default MenuItem;
