/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Helmet } from 'react-helmet';
import { styled } from '@mui/material/styles';
import AltProBrowserTemplate1 from 'src/components/AltProBrowserTemplate1/AltProBrowserTemplate1';
import SubNavSide from 'src/components/SubNavSide/SubNavSide';
import Breadcrumb from 'src/components/Breadcrumb/Breadcrumb';
import InvestorInfoEntity from 'src/components/InvestorInfoEntity/InvestorInfoEntity';
import AmlMenuInvestor from 'src/components/AmlMenuInvestor/AmlMenuInvestor';
import { AmlRootProps } from 'src/types';

const AmlInvestorInfoPerso: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100vw',
  height: '100vh',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Frame201: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `834px`,
  height: `629px`,
  left: `485px`,
  top: `343px`,
});

const Rectangle122: any = styled('div')({
  width: `834px`,
  height: `620px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const AltProBrowserTemplat: any = styled(AltProBrowserTemplate1)(
  ({ theme }: any) => ({
    width: `1440px`,
    height: `1020px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
  })
);

const Frame200: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `343px`,
});

const SubNavSide1: any = styled(SubNavSide)(({ theme }: any) => ({
  margin: `0px`,
}));

const Frame197: any = styled(SubNavSide)(({ theme }: any) => ({
  margin: `0px`,
}));

const Frame204: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `78px`,
  top: `178px`,
});

const Breadcrumb1: any = styled(Breadcrumb)(({ theme }: any) => ({
  margin: `0px`,
}));

const Breadcrumb2: any = styled(Breadcrumb)(({ theme }: any) => ({
  margin: `0px`,
}));

const Breadcrumb3: any = styled(Breadcrumb)(({ theme }: any) => ({
  margin: `0px`,
}));

const Line8: any = styled('div')({
  border: `1px solid rgba(0, 0, 0, 0.12)`,
  width: `1440px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `343px`,
});

const Line9: any = styled('div')({
  border: `1px solid rgba(0, 0, 0, 0.12)`,
  width: `1440px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `343px`,
});

const InvestorInfoEntity1: any = styled(InvestorInfoEntity)(
  ({ theme }: any) => ({
    position: `absolute`,
    left: `627px`,
    top: `391px`,
  })
);

const AmlMenuInvestor1: any = styled(AmlMenuInvestor)(({ theme }: any) => ({
  width: `349px`,
  height: `48px`,
  position: `absolute`,
  left: `545px`,
  top: `221px`,
}));

function AmlRoot(props: AmlRootProps): JSX.Element {
  return (
    <AmlInvestorInfoPerso className={props.className}>
      <Helmet>
        <title>AML/Investor info/Personal info</title>
      </Helmet>
      <Frame201>
        <Rectangle122></Rectangle122>
      </Frame201>
      <AltProBrowserTemplat />
      <Frame200>
        <SubNavSide1 />
        <Frame197 />
      </Frame200>
      <Frame204>
        <Breadcrumb1 />
        <Breadcrumb2 />
        <Breadcrumb3 />
      </Frame204>
      <Line8></Line8>
      <Line9></Line9>
      <InvestorInfoEntity1 />
      <AmlMenuInvestor1 />
    </AmlInvestorInfoPerso>
  );
}

export default AmlRoot;
