/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Back2Image from 'src/assets/images/AltProBrowserTemplate1_Back.png';
import VectorImage from 'src/assets/images/AltProBrowserTemplate1_Vector.png';
import Ellipse2Image from 'src/assets/images/AltProBrowserTemplate1_Ellipse_2.png';
import Ellipse1Image from 'src/assets/images/AltProBrowserTemplate1_Ellipse_1.png';
import Ellipse3Image from 'src/assets/images/AltProBrowserTemplate1_Ellipse_3.png';
import Vector1Image from 'src/assets/images/AltProBrowserTemplate1_Vector_1.png';
import Vector2Image from 'src/assets/images/AltProBrowserTemplate1_Vector_2.png';
import Vector3Image from 'src/assets/images/AltProBrowserTemplate1_Vector_3.png';
import Vector4Image from 'src/assets/images/AltProBrowserTemplate1_Vector_4.png';
import Ellipse31Image from 'src/assets/images/AltProBrowserTemplate1_Ellipse_3_1.png';
import Vector5Image from 'src/assets/images/AltProBrowserTemplate1_Vector_5.png';
import { styled } from '@mui/material/styles';
import Search from 'src/components/Search/Search';
import Back from 'src/components/Back/Back';
import Upload from 'src/components/Upload/Upload';
import Help from 'src/components/Help/Help';
import IconNotification from 'src/components/IconNotification/IconNotification';
import { AltProBrowserTemplate1Props } from 'src/types';

const AltProBrowserTemplat: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1020px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const NavigationTablet: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(212, 212, 211, 1)`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1440px`,
  height: `80px`,
  left: `0px`,
  top: `0px`,
}));

const Rectangle38: any = styled('div')({
  backgroundColor: `rgba(217, 217, 217, 1)`,
  width: `1440px`,
  height: `80px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame3: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `5px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `8px 1103px 8px 16px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flexGrow: `1`,
  left: `253px`,
  top: `16px`,
});

const Search1: any = styled(Search)(({ theme }: any) => ({
  width: `32px`,
  height: `32px`,
  margin: `0px`,
}));

const Back1: any = styled(Back)(({ theme }: any) => ({
  width: `48px`,
  height: `48px`,
  position: `absolute`,
  left: `78px`,
  top: `16px`,
}));

const Back2: any = styled('img')({
  height: `48px`,
  width: `48px`,
  position: `absolute`,
  left: `226px`,
  top: `64px`,
});

const RefreshFill0Wght400G: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `48px`,
  height: `48px`,
  left: `186px`,
  top: `16px`,
  overflow: `hidden`,
});

const Vector: any = styled('img')({
  height: `32px`,
  width: `32px`,
  position: `absolute`,
  left: `8px`,
  top: `8px`,
});

const Ellipse2: any = styled('img')({
  height: `24px`,
  width: `24px`,
  position: `absolute`,
  left: `1209px`,
  top: `31px`,
});

const Ellipse1: any = styled('img')({
  height: `24px`,
  width: `24px`,
  position: `absolute`,
  left: `1249px`,
  top: `31px`,
});

const Ellipse3: any = styled('img')({
  height: `24px`,
  width: `24px`,
  position: `absolute`,
  left: `1289px`,
  top: `31px`,
});

const Rectangle42: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(0, 60, 110, 1)`,
  width: `1440px`,
  height: `80px`,
  position: `absolute`,
  left: `0px`,
  top: `80px`,
}));

const Frame91: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `362.08px`,
  height: `36px`,
  left: `78px`,
  top: `102px`,
});

const InvestorOnboarding: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `22px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `164px`,
  top: `5px`,
}));

const Group: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `140.08px`,
  height: `36px`,
  left: `0px`,
  top: `0px`,
});

const Vector1: any = styled('img')({
  height: `28.05px`,
  width: `137.08px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector2: any = styled('img')({
  height: `5.25px`,
  width: `136.04px`,
  position: `absolute`,
  left: `0px`,
  top: `31px`,
});

const Vector3: any = styled('img')({
  height: `2.58px`,
  width: `1.96px`,
  position: `absolute`,
  left: `137px`,
  top: `26px`,
});

const Vector4: any = styled('img')({
  height: `4.47px`,
  width: `4.48px`,
  position: `absolute`,
  left: `136px`,
  top: `25px`,
});

const Frame4: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `1146px`,
  top: `106px`,
});

const Search2: any = styled(Search)(({ theme }: any) => ({
  width: `24px`,
  height: `24px`,
  margin: `0px`,
}));

const Upload1: any = styled(Upload)(({ theme }: any) => ({
  width: `24px`,
  height: `24px`,
  margin: `0px 0px 0px 30px`,
}));

const Help1: any = styled(Help)(({ theme }: any) => ({
  width: `28px`,
  height: `28px`,
  margin: `0px 0px 0px 30px`,
}));

const IconNotification1: any = styled(IconNotification)(({ theme }: any) => ({
  width: `24px`,
  height: `24px`,
  margin: `0px 0px 0px 30px`,
}));

const Avatar1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  margin: `0px 0px 0px 30px`,
});

const Ellipse31: any = styled('img')({
  height: `24px`,
  width: `24px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Sb: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(33, 33, 33, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `5px`,
  top: `5px`,
}));

const Group27: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22px`,
  height: `5.95px`,
  left: `1191px`,
  top: `-42px`,
});

const Vector5: any = styled('img')({
  height: `22px`,
  width: `5.95px`,
  position: `absolute`,
  left: `14px`,
  top: `14px`,
});

const Frame184: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(16, 84, 138, 1)`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  width: `1440px`,
  height: `57px`,
  left: `0px`,
  top: `160px`,
}));

const Group26: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1440px`,
  height: `48px`,
  left: `0px`,
  top: `972px`,
});

const Rectangle120: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(187, 186, 186, 1)`,
  width: `1440px`,
  height: `48px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Copyright2023UmbFina: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(70, 70, 70, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `1280px`,
  position: `absolute`,
  left: `80px`,
  top: `8px`,
}));

const Rectangle121: any = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 0.12)`,
  width: `1440px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `217px`,
});

function AltProBrowserTemplate1(
  props: AltProBrowserTemplate1Props
): JSX.Element {
  return (
    <AltProBrowserTemplat className={props.className}>
      <NavigationTablet>
        <Rectangle38></Rectangle38>
        <Frame3>
          <Search1 />
        </Frame3>
        <Back1 />
        <Back2 src={Back2Image} loading="lazy" alt={'Back'} />
        <RefreshFill0Wght400G>
          <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
        </RefreshFill0Wght400G>
        <Ellipse2 src={Ellipse2Image} loading="lazy" alt={'Ellipse 2'} />
        <Ellipse1 src={Ellipse1Image} loading="lazy" alt={'Ellipse 1'} />
        <Ellipse3 src={Ellipse3Image} loading="lazy" alt={'Ellipse 3'} />
      </NavigationTablet>
      <Rectangle42></Rectangle42>
      <Frame91>
        <InvestorOnboarding>{`Investor Onboarding`}</InvestorOnboarding>
        <Group>
          <Vector1 src={Vector1Image} loading="lazy" alt={'Vector'} />
          <Vector2 src={Vector2Image} loading="lazy" alt={'Vector'} />
          <Vector3 src={Vector3Image} loading="lazy" alt={'Vector'} />
          <Vector4 src={Vector4Image} loading="lazy" alt={'Vector'} />
        </Group>
      </Frame91>
      <Frame4>
        <Search2 />
        <Upload1 />
        <Help1 />
        <IconNotification1 />
        <Avatar1>
          <Ellipse31 src={Ellipse31Image} loading="lazy" alt={'Ellipse 3'} />
          <Sb>{`SB`}</Sb>
        </Avatar1>
      </Frame4>
      <Group27>
        <Vector5 src={Vector5Image} loading="lazy" alt={'Vector'} />
      </Group27>
      <Frame184></Frame184>
      <Group26>
        <Rectangle120></Rectangle120>
        <Copyright2023UmbFina>
          {`Copyright ©2023 UMB Financial Corporation. All rights reserved. UMB and AltPro are registered service marks of UMB Financial Corporation. For additional disclosures and information, view our Privacy Statement and Legal Terms and Conditions. This page uses cookies as is necessary to provide online service.`}
        </Copyright2023UmbFina>
      </Group26>
      <Rectangle121></Rectangle121>
    </AltProBrowserTemplat>
  );
}

export default AltProBrowserTemplate1;
