/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import MenuItem from 'src/components/MenuItem/MenuItem';
import { AmlMenuInvestorProps } from 'src/types';

const AmlMenuInvestor1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `48px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const MenuItem1: any = styled(MenuItem)(({ theme }: any) => ({
  flexGrow: `1`,
  margin: `0px`,
}));

const MenuItem2: any = styled(MenuItem)(({ theme }: any) => ({
  flexGrow: `1`,
  margin: `0px 0px 0px 2px`,
}));

function AmlMenuInvestor(props: AmlMenuInvestorProps): JSX.Element {
  return (
    <AmlMenuInvestor1 className={props.className}>
      <MenuItem1 />
      <MenuItem2 />
    </AmlMenuInvestor1>
  );
}

export default AmlMenuInvestor;
