/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import SelectField from 'src/components/SelectField/SelectField';
import ListItem1 from 'src/components/ListItem1/ListItem1';
import { ForeignInvestorProps } from 'src/types';

const Property1Default: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: 'auto',
});

const SelectField1: any = styled(SelectField)(({ theme }: any) => ({
  flexGrow: `1`,
  margin: `0px`,
}));

const SelectField2: any = styled(SelectField)(({ theme }: any) => ({
  alignSelf: `stretch`,
  width: `550px`,
  margin: `0px`,
}));

const Frame5: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 2px 2px rgba(0, 0, 0, 0.25)`,
  borderRadius: `0px 0px 4px 4px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `12px 0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: `550px`,
  margin: `0px`,
}));

const ListItem2: any = styled(ListItem1)(({ theme }: any) => ({
  alignSelf: `stretch`,
  height: `40px`,
  margin: `0px`,
}));

const ListItem3: any = styled(ListItem1)(({ theme }: any) => ({
  alignSelf: `stretch`,
  height: `40px`,
  margin: `0px`,
}));

function ForeignInvestor(props: ForeignInvestorProps): JSX.Element {
  return (
    <Property1Default className={props.className}>
      <SelectField1 />
      {false && <SelectField2 />}
      {false && (
        <Frame5>
          <ListItem2 />
          <ListItem3 />
        </Frame5>
      )}
    </Property1Default>
  );
}

export default ForeignInvestor;
