/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import CheckBoxCircle from 'src/components/CheckBoxCircle/CheckBoxCircle';
import H4 from 'src/components/H4/H4';
import Body75Rem from 'src/components/Body75Rem/Body75Rem';
import { SubNavSideProps } from 'src/types';

const StateInactive: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `48px 105px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const Frame195: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const CheckBoxCircle1: any = styled(CheckBoxCircle)(({ theme }: any) => ({
  width: `24px`,
  height: `24px`,
  margin: `0px`,
}));

const H41: any = styled(H4)(({ theme }: any) => ({
  margin: `0px 0px 0px 8px`,
}));

const Frame196: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 0px 0px 32px`,
  boxSizing: `border-box`,
  margin: `8px 0px 0px 0px`,
});

const Body75Rem1: any = styled(Body75Rem)(({ theme }: any) => ({
  width: `227px`,
  margin: `0px`,
}));

function SubNavSide(props: SubNavSideProps): JSX.Element {
  return (
    <StateInactive className={props.className}>
      <Frame195>
        <CheckBoxCircle1 />
        <H41 />
      </Frame195>
      <Frame196>
        <Body75Rem1 />
      </Frame196>
    </StateInactive>
  );
}

export default SubNavSide;
