/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Card2Props } from 'src/types';
const useCard2 = (props: Card2Props) => {
  let data: any = {};
  const bookNowClicked = (): any => {};

  let fns: any = { bookNowClicked };
  return { data, fns };
};

export default useCard2;
