/**********************************************************************
 *
 *   Types file generated by Quest
 *
 *   Types for the components props go in this file
 *   To set up custom types for the components props, edit the corresponding types in this file
 *   Once you edit a type to no longer by "any", be careful to not override it on your next export
 *   Verify diff before merging
 *
 *   For help and further details refer to:
 *   https://docs.quest.ai/react/fundamentals/exporting-code
 *
 *
 **********************************************************************/


export interface SampleCardProps {
  className?: any;
  metadata: any;
}


export interface SampleCardGridProps {
  className?: any;
}


export interface Frame2Props {
  className?: any;
}


export interface AmlRootProps {
  className?: any;
}


export interface AltProBrowserTemplate1Props {
  className?: any;
}


export interface SearchProps {
  className?: any;
}


export interface BackProps {
  className?: any;
}


export interface UploadProps {
  className?: any;
}


export interface HelpProps {
  className?: any;
}


export interface SubNavSideProps {
  className?: any;
}


export interface CheckBoxCircleProps {
  className?: any;
}


export interface H4Props {
  className?: any;
}


export interface Body75RemProps {
  className?: any;
}


export interface BreadcrumbProps {
  className?: any;
}


export interface InvestorInfoEntityProps {
  className?: any;
}


export interface EntityTypeProps {
  className?: any;
}


export interface SelectFieldProps {
  className?: any;
}


export interface MenuDownProps {
  className?: any;
}


export interface AccountNameProps {
  className?: any;
}


export interface InputFieldProps {
  className?: any;
}


export interface TaxIdTypeProps {
  className?: any;
}


export interface IdNumberProps {
  className?: any;
}


export interface ForeignInvestorProps {
  className?: any;
}


export interface AccreditationProps {
  className?: any;
}


export interface AmlMenuInvestorProps {
  className?: any;
}


export interface MenuItemProps {
  className?: any;
}
