/**********************************************************************
 *
 *   Types file generated by Quest
 *
 *   Types for the components props go in this file
 *   To set up custom types for the components props, edit the corresponding types in this file
 *   Once you edit a type to no longer by "any", be careful to not override it on your next export
 *   Verify diff before merging
 *
 *   For help and further details refer to:
 *   https://docs.quest.ai/react/fundamentals/exporting-code
 *
 *
 **********************************************************************/









export interface Card2Props {
  className?: any;
  hotel: any;
};





export interface SubNavProps {
  className?: any;
};









export interface CheckBoxCircleProps {
  className?: any;
}







export interface H4Props {
  className?: any;
}







export interface Body75RemProps {
  className?: any;
}















export interface SubNavSideProps {
  className?: any;
}

export interface SubNavSideProps {
  className?: any;
}





export interface MenuItemProps {
  className?: any;
};










export interface SampleCardProps {
  className?: any;
  metadata: any;
}









export interface SampleCardGridProps {
  className?: any;
}









export interface Frame2Props {
  className?: any;
}
