/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import VectorImage from 'src/assets/images/CheckBoxCircle_Vector.png';
import Vector1Image from 'src/assets/images/CheckBoxCircle_Vector_1.png';
import { styled } from '@mui/material/styles';
import { CheckBoxCircleProps } from 'src/types';

const Property1Default: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `24px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Vector: any = styled('img')({
  height: `24px`,
  width: `24px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector1: any = styled('img')({
  height: `18px`,
  width: `18px`,
  position: `absolute`,
  left: `3px`,
  top: `3px`,
});

function CheckBoxCircle(props: CheckBoxCircleProps): JSX.Element {
  return (
    <Property1Default className={props.className}>
      <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
      <Vector1 src={Vector1Image} loading="lazy" alt={'Vector'} />
    </Property1Default>
  );
}

export default CheckBoxCircle;
